### ISSUE TITLE
How to Drag and Drop Items Horizontally as well?

### ISSUE THREAD

**Issue by Yousaf128** [MortezaNedaei/DragListAdater#1]
How to drag and drop items horizontally same like Trello board. Thanks

**Comment by MortezaNedaei** [comment]
- To have a horizontal list, change the RecyclerView direction in `main_fragment.xml` using `android:orientation="horizontal"`
> You may need to use `app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"` to make a grid layout instead
- You can change the movement flags for RecyclerView direction like this:
```kt
private val touchHelperCallback = object : ItemTouchHelper.Callback() {

        override fun getMovementFlags(
            recyclerView: RecyclerView,
            viewHolder: RecyclerView.ViewHolder
        ): Int {
            return makeMovementFlags(
                ItemTouchHelper.UP or 
                ItemTouchHelper.DOWN or
                ItemTouchHelper.LEFT or
                ItemTouchHelper.RIGHT,
                0,
            )
        }
```

- Don't forget to update animation resource in the RecyclerView `ListAdapter`
